name: star_wars
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  shared_preferences: ^2.0.5
  permission_handler: ^10.2.0
  material: ^1.0.0+2
  easy_localization: ^3.0.0
  cached_network_image: ^3.2.0
  uuid: ^3.0.6
  flutter_inappwebview: ^5.6.0+2
  provider: ^6.0.3
  flutter_hooks: ^0.18.2
  internet_connection_checker: ^0.0.1+3
  fluttertoast: ^8.0.9
  lottie: ^1.4.2
  google_fonts: ^4.0.3
  dio: ^5.1.1
  json_annotation: ^4.8.1
  rflutter_alert: ^2.0.4
  styled_text: ^5.1.0
  connectivity_plus: ^3.0.4
  package_info_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.1
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    # default
    - assets/animations/
    - assets/images/app/
    - assets/translations/